TARGET = retro-go-nes

DEBUG = 1
#OPT = -Og -ggdb
OPT = -O0 -ggdb3
#-fsanitize=address

BUILD_DIR = build


C_SOURCES =  \
odroid_input.c \
odroid_netplay.c \
odroid_overlay.c \
odroid_sdcard.c \
odroid_system.c \
odroid_display.c \
odroid_audio.c \
gw_lcd.c \
loaded_nes_rom.c \
porting.c \
../external/fceumm-go/src/boards/09-034a.c \
../external/fceumm-go/src/boards/3d-block.c \
../external/fceumm-go/src/boards/8in1.c \
../external/fceumm-go/src/boards/12in1.c \
../external/fceumm-go/src/boards/15.c \
../external/fceumm-go/src/boards/18.c \
../external/fceumm-go/src/boards/28.c \
../external/fceumm-go/src/boards/31.c \
../external/fceumm-go/src/boards/32.c \
../external/fceumm-go/src/boards/33.c \
../external/fceumm-go/src/boards/34.c \
../external/fceumm-go/src/boards/40.c \
../external/fceumm-go/src/boards/41.c \
../external/fceumm-go/src/boards/42.c \
../external/fceumm-go/src/boards/43.c \
../external/fceumm-go/src/boards/46.c \
../external/fceumm-go/src/boards/50.c \
../external/fceumm-go/src/boards/51.c \
../external/fceumm-go/src/boards/57.c \
../external/fceumm-go/src/boards/60.c \
../external/fceumm-go/src/boards/62.c \
../external/fceumm-go/src/boards/65.c \
../external/fceumm-go/src/boards/67.c \
../external/fceumm-go/src/boards/68.c \
../external/fceumm-go/src/boards/69.c \
../external/fceumm-go/src/boards/71.c \
../external/fceumm-go/src/boards/72.c \
../external/fceumm-go/src/boards/77.c \
../external/fceumm-go/src/boards/79.c \
../external/fceumm-go/src/boards/80.c \
../external/fceumm-go/src/boards/82.c \
../external/fceumm-go/src/boards/88.c \
../external/fceumm-go/src/boards/91.c \
../external/fceumm-go/src/boards/96.c \
../external/fceumm-go/src/boards/99.c \
../external/fceumm-go/src/boards/103.c \
../external/fceumm-go/src/boards/104.c \
../external/fceumm-go/src/boards/106.c \
../external/fceumm-go/src/boards/108.c \
../external/fceumm-go/src/boards/112.c \
../external/fceumm-go/src/boards/116.c \
../external/fceumm-go/src/boards/117.c \
../external/fceumm-go/src/boards/120.c \
../external/fceumm-go/src/boards/121.c \
../external/fceumm-go/src/boards/126-422-534.c \
../external/fceumm-go/src/boards/134.c \
../external/fceumm-go/src/boards/151.c \
../external/fceumm-go/src/boards/156.c \
../external/fceumm-go/src/boards/162.c \
../external/fceumm-go/src/boards/163.c \
../external/fceumm-go/src/boards/164.c \
../external/fceumm-go/src/boards/168.c \
../external/fceumm-go/src/boards/170.c \
../external/fceumm-go/src/boards/175.c \
../external/fceumm-go/src/boards/177.c \
../external/fceumm-go/src/boards/178.c \
../external/fceumm-go/src/boards/183.c \
../external/fceumm-go/src/boards/185.c \
../external/fceumm-go/src/boards/186.c \
../external/fceumm-go/src/boards/187.c \
../external/fceumm-go/src/boards/189.c \
../external/fceumm-go/src/boards/190.c \
../external/fceumm-go/src/boards/193.c \
../external/fceumm-go/src/boards/195.c \
../external/fceumm-go/src/boards/199.c \
../external/fceumm-go/src/boards/206.c \
../external/fceumm-go/src/boards/208.c \
../external/fceumm-go/src/boards/218.c \
../external/fceumm-go/src/boards/222.c \
../external/fceumm-go/src/boards/225.c \
../external/fceumm-go/src/boards/228.c \
../external/fceumm-go/src/boards/230.c \
../external/fceumm-go/src/boards/232.c \
../external/fceumm-go/src/boards/233.c \
../external/fceumm-go/src/boards/234.c \
../external/fceumm-go/src/boards/235.c \
../external/fceumm-go/src/boards/236.c \
../external/fceumm-go/src/boards/237.c \
../external/fceumm-go/src/boards/244.c \
../external/fceumm-go/src/boards/246.c \
../external/fceumm-go/src/boards/252.c \
../external/fceumm-go/src/boards/253.c \
../external/fceumm-go/src/boards/267.c \
../external/fceumm-go/src/boards/268.c \
../external/fceumm-go/src/boards/269.c \
../external/fceumm-go/src/boards/272.c \
../external/fceumm-go/src/boards/283.c \
../external/fceumm-go/src/boards/291.c \
../external/fceumm-go/src/boards/293.c \
../external/fceumm-go/src/boards/294.c \
../external/fceumm-go/src/boards/310.c \
../external/fceumm-go/src/boards/319.c \
../external/fceumm-go/src/boards/326.c \
../external/fceumm-go/src/boards/330.c \
../external/fceumm-go/src/boards/334.c \
../external/fceumm-go/src/boards/351.c \
../external/fceumm-go/src/boards/353.c \
../external/fceumm-go/src/boards/354.c \
../external/fceumm-go/src/boards/356.c \
../external/fceumm-go/src/boards/357.c \
../external/fceumm-go/src/boards/359.c \
../external/fceumm-go/src/boards/360.c \
../external/fceumm-go/src/boards/364.c \
../external/fceumm-go/src/boards/368.c \
../external/fceumm-go/src/boards/369.c \
../external/fceumm-go/src/boards/370.c \
../external/fceumm-go/src/boards/372.c \
../external/fceumm-go/src/boards/375.c \
../external/fceumm-go/src/boards/376.c \
../external/fceumm-go/src/boards/377.c \
../external/fceumm-go/src/boards/380.c \
../external/fceumm-go/src/boards/382.c \
../external/fceumm-go/src/boards/383.c \
../external/fceumm-go/src/boards/389.c \
../external/fceumm-go/src/boards/390.c \
../external/fceumm-go/src/boards/391.c \
../external/fceumm-go/src/boards/393.c \
../external/fceumm-go/src/boards/395.c \
../external/fceumm-go/src/boards/396.c \
../external/fceumm-go/src/boards/401.c \
../external/fceumm-go/src/boards/403.c \
../external/fceumm-go/src/boards/410.c \
../external/fceumm-go/src/boards/411.c \
../external/fceumm-go/src/boards/414.c \
../external/fceumm-go/src/boards/416.c \
../external/fceumm-go/src/boards/417.c \
../external/fceumm-go/src/boards/428.c \
../external/fceumm-go/src/boards/431.c \
../external/fceumm-go/src/boards/432.c \
../external/fceumm-go/src/boards/433.c \
../external/fceumm-go/src/boards/434.c \
../external/fceumm-go/src/boards/436.c \
../external/fceumm-go/src/boards/437.c \
../external/fceumm-go/src/boards/438.c \
../external/fceumm-go/src/boards/441.c \
../external/fceumm-go/src/boards/443.c \
../external/fceumm-go/src/boards/444.c \
../external/fceumm-go/src/boards/449.c \
../external/fceumm-go/src/boards/452.c \
../external/fceumm-go/src/boards/455.c \
../external/fceumm-go/src/boards/456.c \
../external/fceumm-go/src/boards/460.c \
../external/fceumm-go/src/boards/463.c \
../external/fceumm-go/src/boards/465.c \
../external/fceumm-go/src/boards/466.c \
../external/fceumm-go/src/boards/467.c \
../external/fceumm-go/src/boards/468.c \
../external/fceumm-go/src/boards/516.c \
../external/fceumm-go/src/boards/533.c \
../external/fceumm-go/src/boards/539.c \
../external/fceumm-go/src/boards/554.c \
../external/fceumm-go/src/boards/558.c \
../external/fceumm-go/src/boards/603-5052.c \
../external/fceumm-go/src/boards/8157.c \
../external/fceumm-go/src/boards/8237.c \
../external/fceumm-go/src/boards/411120-c.c \
../external/fceumm-go/src/boards/830118C.c \
../external/fceumm-go/src/boards/830134C.c \
../external/fceumm-go/src/boards/a9746.c \
../external/fceumm-go/src/boards/ac-08.c \
../external/fceumm-go/src/boards/addrlatch.c \
../external/fceumm-go/src/boards/ax40g.c \
../external/fceumm-go/src/boards/ax5705.c \
../external/fceumm-go/src/boards/bandai.c \
../external/fceumm-go/src/boards/bb.c \
../external/fceumm-go/src/boards/bj56.c \
../external/fceumm-go/src/boards/bmc42in1r.c \
../external/fceumm-go/src/boards/bmc64in1nr.c \
../external/fceumm-go/src/boards/bmc60311c.c \
../external/fceumm-go/src/boards/bmc80013b.c \
../external/fceumm-go/src/boards/bmc830425C4391t.c \
../external/fceumm-go/src/boards/bmcctc09.c \
../external/fceumm-go/src/boards/bmcgamecard.c \
../external/fceumm-go/src/boards/bmck3006.c \
../external/fceumm-go/src/boards/bmck3033.c \
../external/fceumm-go/src/boards/bmck3036.c \
../external/fceumm-go/src/boards/bmcl6in1.c \
../external/fceumm-go/src/boards/BMW8544.c \
../external/fceumm-go/src/boards/bonza.c \
../external/fceumm-go/src/boards/bs-5.c \
../external/fceumm-go/src/boards/cheapocabra.c \
../external/fceumm-go/src/boards/cityfighter.c \
../external/fceumm-go/src/boards/coolgirl.c \
../external/fceumm-go/src/boards/dance2000.c \
../external/fceumm-go/src/boards/datalatch.c \
../external/fceumm-go/src/boards/dream.c \
../external/fceumm-go/src/boards/edu2000.c \
../external/fceumm-go/src/boards/eeprom_93C66.c \
../external/fceumm-go/src/boards/eh8813a.c \
../external/fceumm-go/src/boards/fceu-emu2413.c \
../external/fceumm-go/src/boards/et-100.c \
../external/fceumm-go/src/boards/et-4320.c \
../external/fceumm-go/src/boards/f-15.c \
../external/fceumm-go/src/boards/famicombox.c \
../external/fceumm-go/src/boards/faridunrom.c \
../external/fceumm-go/src/boards/ffe.c \
../external/fceumm-go/src/boards/fk23c.c \
../external/fceumm-go/src/boards/gn26.c \
../external/fceumm-go/src/boards/h2288.c \
../external/fceumm-go/src/boards/hp10xx_hp20xx.c \
../external/fceumm-go/src/boards/hp898f.c \
../external/fceumm-go/src/boards/jyasic.c \
../external/fceumm-go/src/boards/karaoke.c \
../external/fceumm-go/src/boards/KG256.c \
../external/fceumm-go/src/boards/kof97.c \
../external/fceumm-go/src/boards/KS7012.c \
../external/fceumm-go/src/boards/KS7013.c \
../external/fceumm-go/src/boards/KS7016.c \
../external/fceumm-go/src/boards/KS7017.c \
../external/fceumm-go/src/boards/KS7030.c \
../external/fceumm-go/src/boards/KS7031.c \
../external/fceumm-go/src/boards/KS7032.c \
../external/fceumm-go/src/boards/KS7037.c \
../external/fceumm-go/src/boards/KS7057.c \
../external/fceumm-go/src/boards/le05.c \
../external/fceumm-go/src/boards/lh32.c \
../external/fceumm-go/src/boards/lh51.c \
../external/fceumm-go/src/boards/lh53.c \
../external/fceumm-go/src/boards/malee.c \
../external/fceumm-go/src/boards/mihunche.c \
../external/fceumm-go/src/boards/mmc1.c \
../external/fceumm-go/src/boards/mmc2and4.c \
../external/fceumm-go/src/boards/mmc3.c \
../external/fceumm-go/src/boards/mmc5.c \
../external/fceumm-go/src/boards/n106.c \
../external/fceumm-go/src/boards/n625092.c \
../external/fceumm-go/src/boards/novel.c \
../external/fceumm-go/src/boards/onebus.c \
../external/fceumm-go/src/boards/pec-586.c \
../external/fceumm-go/src/boards/resetnromxin1.c \
../external/fceumm-go/src/boards/resettxrom.c \
../external/fceumm-go/src/boards/rt-01.c \
../external/fceumm-go/src/boards/SA-9602B.c \
../external/fceumm-go/src/boards/sachen.c \
../external/fceumm-go/src/boards/sheroes.c \
../external/fceumm-go/src/boards/sl1632.c \
../external/fceumm-go/src/boards/subor.c \
../external/fceumm-go/src/boards/super40in1.c \
../external/fceumm-go/src/boards/supervision.c \
../external/fceumm-go/src/boards/t-227-1.c \
../external/fceumm-go/src/boards/t-262.c \
../external/fceumm-go/src/boards/tengen.c \
../external/fceumm-go/src/boards/tf-1201.c \
../external/fceumm-go/src/boards/txcchip.c \
../external/fceumm-go/src/boards/unrom512.c \
../external/fceumm-go/src/boards/vrc1.c \
../external/fceumm-go/src/boards/vrc2and4.c \
../external/fceumm-go/src/boards/vrc3.c \
../external/fceumm-go/src/boards/vrc6.c \
../external/fceumm-go/src/boards/vrc7.c \
../external/fceumm-go/src/boards/vrc7p.c \
../external/fceumm-go/src/boards/yoko.c \
../external/fceumm-go/src/cheat.c \
../external/fceumm-go/src/crc32.c \
../external/fceumm-go/src/fceu-cart.c \
../external/fceumm-go/src/fceu-endian.c \
../external/fceumm-go/src/fceu-sound.c \
../external/fceumm-go/src/fceu-state.c \
../external/fceumm-go/src/fceu.c \
../external/fceumm-go/src/fds_apu.c \
../external/fceumm-go/src/fds.c \
../external/fceumm-go/src/filter.c \
../external/fceumm-go/src/general.c \
../external/fceumm-go/src/ines.c \
../external/fceumm-go/src/input.c \
../external/fceumm-go/src/md5.c \
../external/fceumm-go/src/nsf.c \
../external/fceumm-go/src/palette.c \
../external/fceumm-go/src/ppu.c \
../external/fceumm-go/src/video.c \
../external/fceumm-go/src/x6502.c \
../external/fceumm-go/src/drivers/libretro/libretro-common/streams/memory_stream.c \
nes-fceumm/main.c \

PREFIX = 

CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

C_DEFS =  \
-DIS_LITTLE_ENDIAN -DFCEU_VERSION_NUMERIC=9813 -DTARGET_GNW -DFCEU_NO_MALLOC -DLINUX_EMU -DFCEU_LOW_RAM -DENABLE_EMULATOR_NES -DFORCE_NOFRENDO=0 -DNES_MAPPER_NSF

#-DFCEU_ENABLE_GAMEGENIE_ROM -DCHEAT_CODES=1

C_INCLUDES =  \
-I. \
-I../Core/Inc/porting/nes_fceu \
-I../external/fceumm-go/src/ \
-I../external/fceumm-go/src/drivers/libretro/libretro-common/include \
-I../retro-go-stm32/components/odroid \
-I./nes-fceumm


ASFLAGS = $(AS_DEFS) $(AS_INCLUDES) $(OPT) -fdata-sections -ffunction-sections
CFLAGS  = $(C_DEFS) $(C_INCLUDES) `sdl2-config --cflags` $(OPT) -fdata-sections -ffunction-sections
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

#LIBS = -lm `sdl2-config --libs`
LIBS = -lm `sdl2-config --libs`
LDFLAGS = $(LIBS)

all: outDir $(BUILD_DIR)/$(TARGET).elf

OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

outDir:
	mkdir -p build
	if ! [ -f ./build/config.h ]; then \
		touch build/config.h; \
	fi
	if ! [ -f ./build/mappers.h ]; then \
		touch build/mappers.h; \
	fi

$(BUILD_DIR)/%.o: %.c Makefile.nes | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile.nes
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR):
	mkdir -p $@

clean:
	-rm -fR $(BUILD_DIR)

-include $(wildcard $(BUILD_DIR)/*.d)
